apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
      - name: node-red
        image: nodered/node-red
        ports:
        - containerPort: 1880
        volumeMounts:
        - name: my-volume
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-pvc