apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-pv
spec:
  capacity:
    storage: {{ .Values.pvStorage }]
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /home/user/node_red_data  
